/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.04.00 

  Company:
      Microchip Technology, Inc.
 
  File Name:
     DINv4_26_2BPP_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx_config.h>
#include <gfx/gfx_types_resource.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Format Check
 *****************************************************************************/
#ifndef GFX_RESOURCE_FORMAT_VERSION
    #if(GRAPHICS_LIBRARY_VERSION != 0x0401)
    #warning "It is suggested to use Graphics Library version 4.01 or later with this version of GRC."
    #endif
#elif(GFX_RESOURCE_FORMAT_VERSION != 0x0101)
#warning "It is suggested to use Graphics Library with the resource format version 1.01 with this version of GRC."
#endif


/*****************************************************************************
 * SECTION: External Memory Font Raster Buffer Size Check
 *****************************************************************************/
#if (GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE < 174)
#error The GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE defined in system_config header file is smaller than the require size needed to support these external fonts.
#error Please define "#define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE (174)" in system_config.h.
#endif

#if (GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE > 174)
#warning The GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE defined in system_config header file is larger than is needed for these external fonts.
#endif


/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_EXTERNAL_DISABLE
#error The GFX_CONFIG_FONT_EXTERNAL_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * Installed Font Structure
 * Label: DINv4_26_2BPP
 * Description:  Height: 29 pixels, 2 bits per pixel, Range: ' ' to 'ÿ'
 ***********************************/
const GFX_RESOURCE_HDR DINv4_26_2BPP = 
{
    .type = (GFX_RESOURCE_MEMORY_EXTERNAL | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.extAddress = (uint32_t) 0x00000000,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 1,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x00FF,
    .resource.font.header.height = 0x001D,
};
