/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microchip_grc_Emulator */

#ifndef _Included_com_microchip_grc_Emulator
#define _Included_com_microchip_grc_Emulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxColorSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxColorSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxColorGet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxColorGet
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxLineDraw
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxLineDraw
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxLineStyleSet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxLineStyleSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxLineStyleGet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxLineStyleGet
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxFontSet
 * Signature: (Lcom/microchip/grc/GFXResourceHeader;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxFontSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxFontGet
 * Signature: ()Lcom/microchip/grc/GFXResourceHeader;
 */
JNIEXPORT jobject JNICALL Java_com_microchip_grc_Emulator_gfxFontGet
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxScreenClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxScreenClear
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextAreaBottomSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxTextAreaBottomSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextAreaLeftSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxTextAreaLeftSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextAreaRightSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxTextAreaRightSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextAreaTopSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_gfxTextAreaTopSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextCursorPositionSet
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxTextCursorPositionSet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    gfxTextStringDraw
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_gfxTextStringDraw
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    validateScreen
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_microchip_grc_Emulator_validateScreen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    setFontFileName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_setFontFileName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microchip_grc_Emulator_init
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    getDisplayHorizontalResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_getDisplayHorizontalResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_grc_Emulator
 * Method:    getDisplayVerticalResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_grc_Emulator_getDisplayVerticalResolution
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
